[package]
name = "odra-bdd"
description = "BDD helper for Odra smart contracts."

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
odra = { path = "../odra", version = "2.9.1" }

cucumber = { workspace = true}
futures = { workspace = true }
