[package]
name = "odra-bdd"
description = "BDD helper for Odra smart contracts."
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cucumber.workspace = true
futures.workspace = true
derive_more.workspace = true
odra = { path = "../odra", version = "2.3.1" }
