[package]
name = "benchmark"
description = "Benchmarking contracts and tools for Odra Framework"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
odra = { path = "../odra" }
odra-modules = { path = "../modules" }
odra-test = { path = "../odra-test", optional = true }

base64 = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
serde_json = { workspace = true }

[[bin]]
name = "benchmark_build_contract"
path = "bin/build_contract.rs"
test = false

[[bin]]
name = "benchmark_build_schema"
path = "bin/build_schema.rs"
test = false

[[bin]]
name = "benchmark"
path = "bin/benchmark.rs"
required-features = ["odra-test"]
test = false

[[bin]]
name = "evaluate_benchmark"
path = "bin/evaluate_benchmark.rs"
test = false

[features]
benchmark = ["odra-test"]
default = []
