[package]
name = "odra-wasm-client-builder"
description = "Wasm client"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
odra-schema = { workspace = true }

convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4.0"
