[package]
name = "odra-test-env"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odra-types = { path = "../types" }
cfg-if = "1.0.0"

[features]
default = [ "mock-vm" ]
mock-vm = [ ]
wasm-test = [ ]