[package]
name = "odra-casper-livenet"
edition = "2021"
description = "Odra Casper library for live Casper blockchain interaction."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
casper-types = { workspace = true, features = ["datasize", "json-schema"] }
#casper-execution-engine = { workspace = true }
#casper-hashing = { version = "2.0.0", default-features = false }
odra-casper-shared = { path = "../shared" }
odra-casper-types = { path = "../types" }
odra-types = { path = "../../types", default-features = false, features = [] }
#odra-mock-vm = { path = "../../mock-vm/backend" }
ref_thread_local = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
hex = "0.4.3"
jsonrpc-lite = "0.6.0"
blake2 = { version = "0.9.0", default-features = false }
dotenv = "0.15.0"
prettycli = "0.1.1"
schemars = "0.8.5"
datasize = "0.2.14"
thiserror = "1.0.40"
itertools = "0.10.5"
hex-buffer-serde = "0.4.0"
hex_fmt = "0.3.0"
once_cell = "1.18.0"
base16 = "0.2.1"
http_req = { version = "0.9.2", default-features = false, features = ["rust-tls"] }
web-sys = { version = "0.3.64", features = ["console"]}
gloo-net = "0.3.0"
serde-wasm-bindgen = "0.5.0"

[dev-dependencies]
tokio = { version = "1.29.1", features = ["macros"] }
tokio-test = "0.4.2"