[package]
name = "odra-casper-livenet"
version = "0.2.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra"
description = "Odra Casper library for live Casper blockchain interaction."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]

[dependencies]
casper-types = "1.5.0"
casper-node = "1.4"
casper-execution-engine = "3.0.0"
casper-hashing = "1.4.3"
odra-casper-shared = { version = "0.2.0", path = "../shared" }
odra-casper-types = { version = "0.2.0", path = "../types" }
odra-types = { version = "0.2.0", path = "../../types" }
odra-mock-vm = { version = "0.2.0", path = "../../mock-vm/backend" }
ref_thread_local = "0.1.1"
serde = "1.0"
serde_json = { version = "1.0", features = ["raw_value"] }
hex = "0.4.3"
reqwest = { version = "0.11.16", features = ["blocking", "json"] }
jsonrpc-lite = "0.6.0"
blake2 = { version = "0.9.0", default-features = false }
dotenv = "0.15.0"