[package]
name = "odra-casper-livenet"
edition = "2021"
description = "Odra Casper library for live Casper blockchain interaction."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
casper-execution-engine = { workspace = true }
casper-hashing = "2.0.0"
odra-casper-shared = { path = "../shared", version = "0.7.0" }
odra-types = { path = "../../types", version = "0.7.0" }
odra-mock-vm = { path = "../../mock-vm/backend", version = "0.7.0" }
ref_thread_local = "0.1.1"
serde = "1.0"
serde_json = { version = "1.0", features = ["raw_value"] }
hex = "0.4.3"
reqwest = { version = "0.11.16", features = ["blocking", "json"] }
jsonrpc-lite = "0.7.0"
blake2 = { version = "0.9.0", default-features = false }
dotenv = "0.15.0"
prettycli = "0.1.1"
schemars = "0.8.5"
datasize = "0.2.14"
thiserror = "1.0.40"
itertools = "0.10.5"
