[package]
name = "odra-modules"
version = "0.1.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra"
description = "Collection of reusable modules"
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm"]


[dependencies]
odra-types = { version = "0.1.0", path = "../types" }
odra-proc-macros = { version = "0.1.0", path = "../lang/proc_macros" }
odra-env = { version = "0.1.0", path = "../env", default-features = false, optional = true }
odra-primitives = { version = "0.1.0", path = "../primitives", default-features = false, optional = true }
delegate = "0.7.0"

[features]
default = [ "mock-vm" ]
mock-vm = [ "odra-env/mock-vm", "odra-primitives/mock-vm" ]
wasm = [ "odra-env/wasm", "odra-primitives/wasm"]
wasm-test = [ "odra-env/wasm-test", "odra-primitives/wasm-test" ]