[package]
name = "odra-modules"
version = "0.8.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra"
description = "Collection of reusable Odra modules."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm"]

[dependencies]
odra = { path = "../odra", version = "0.8.0", default-features = false }
casper-event-standard = "0.4.1"
hex = { version = "0.4.3", default-features = false }

[[bin]]
name = "build_contract"
path = "bin/build_contract.rs"

[[bin]]
name = "build_schema"
path = "bin/build_schema.rs"

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
