[package]
name = "odra-modules"
version = "0.2.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra"
description = "Collection of reusable Odra modules."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm"]

[dependencies]
odra = { version = "0.2.0", path = "../core", default-features = false }
hex = "0.4.3"
sha3 = "0.10.6"

[features]
default = [ "casper" ]
mock-vm = [ "odra/mock-vm" ]
casper = [ "odra/casper" ]
casper-livenet = ["odra/casper-livenet"]
