[package]
name = "odra-modules"
description = "Collection of reusable Odra modules."

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
base64 = { workspace = true }
odra = { path = "../odra", version = "2.7.1", default-features = false }
casper-eip-712 = { version = "1.2.0", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
odra-build = { path = "../odra-build", version = "2.7.1" }

[dev-dependencies]
odra-test = { path = "../odra-test", version = "2.7.1" }

[build-dependencies]
odra-build = { path = "../odra-build", version = "2.7.1" }

[features]
default = ["eip712"]
disable-allocator = ["odra/disable-allocator"]
eip712 = ["casper-eip-712"]

[[bin]]
name = "odra_modules_build_contract"
path = "bin/build_contract.rs"
test = false

[[bin]]
name = "odra_modules_build_schema"
path = "bin/build_schema.rs"
test = false

[lints.rust]
missing_docs = "warn"
