[package]
name = "odra-module"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { path = "../core", default-features = false, optional = true }

[features]
default = [ "mock-vm" ]
mock-vm = [ "odra/mock-vm" ]
wasm = [ "odra/wasm" ]
wasm-test = [ "odra/wasm-test" ]
