[[contracts]]
fqn = "erc20::Erc20"

[[contracts]]
fqn = "erc721_token::Erc721Token"

[[contracts]]
fqn = "erc721_receiver::Erc721Receiver"

[[contracts]]
fqn = "erc1155_token::Erc1155Token"

[[contracts]]
fqn = "erc1155_receiver::Erc1155Receiver"

[[contracts]]
fqn = "wrapped_native::WrappedNativeToken"

[[contracts]]
fqn = "access::Ownable"

[[contracts]]
fqn = "ownable_2step::Ownable2Step"

[[contracts]]
fqn = "cep78::token::Cep78"

[[contracts]]
fqn = "cep78::utils::MockContract"

[[contracts]]
fqn = "cep78::utils::MockDummyContract"

[[contracts]]
fqn = "cep78::utils::MockTransferFilterContract"

