[[contracts]]
name = "Erc20"
fqn = "odra_modules::Erc20"
#
#[[contracts]]
#name = "erc721_token"
#fqn = "odra_modules::erc721_token::Erc721Token"
#
#[[contracts]]
#name = "erc721_receiver"
#fqn = "odra_modules::erc721_receiver::Erc721Receiver"
#
#[[contracts]]
#name = "erc1155_token"
#fqn = "odra_modules::erc1155_token::Erc1155Token"
#
#[[contracts]]
#name = "erc1155_receiver"
#fqn = "odra_modules::erc1155_receiver::Erc1155Receiver"

[[contracts]]
name = "WrappedNativeToken"
fqn = "odra_modules::wrapped_native::WrappedNativeToken"

#[[contracts]]
#name = "ownable"
#fqn = "odra_modules::access::Ownable"
#
#[[contracts]]
#name = "ownable2_step"
#fqn = "odra_modules::access::Ownable2Step"
#
