[[contracts]]
name = "Erc20"
fqn = "odra_modules::Erc20"

[[contracts]]
name = "Erc721Token"
fqn = "odra_modules::erc721_token::Erc721Token"

[[contracts]]
name = "Erc721Receiver"
fqn = "odra_modules::erc721_receiver::Erc721Receiver"

[[contracts]]
name = "Erc1155Token"
fqn = "odra_modules::erc1155_token::Erc1155Token"

[[contracts]]
name = "Erc1155Receiver"
fqn = "odra_modules::erc1155_receiver::Erc1155Receiver"

[[contracts]]
name = "WrappedNativeToken"
fqn = "odra_modules::wrapped_native::WrappedNativeToken"

[[contracts]]
name = "Ownable"
fqn = "odra_modules::access::Ownable"

[[contracts]]
name = "Ownable2Step"
fqn = "odra_modules::ownable_2step::Ownable2Step"

