[[contracts]]
fqn = "odra_modules::Erc20"

[[contracts]]
fqn = "odra_modules::erc721_token::Erc721Token"

[[contracts]]
fqn = "odra_modules::erc721_receiver::Erc721Receiver"

[[contracts]]
fqn = "odra_modules::erc1155_token::Erc1155Token"

[[contracts]]
fqn = "odra_modules::erc1155_receiver::Erc1155Receiver"

[[contracts]]
fqn = "odra_modules::wrapped_native::WrappedNativeToken"

[[contracts]]
fqn = "odra_modules::access::Ownable"

[[contracts]]
fqn = "odra_modules::ownable_2step::Ownable2Step"

