[[contracts]]
fqn = "erc20::Erc20"

[[contracts]]
fqn = "erc721_token::Erc721Token"

[[contracts]]
fqn = "erc721_receiver::Erc721Receiver"

[[contracts]]
fqn = "erc1155_token::Erc1155Token"

[[contracts]]
fqn = "erc1155_receiver::Erc1155Receiver"

[[contracts]]
fqn = "wrapped_native::WrappedNativeToken"

[[contracts]]
fqn = "access::Ownable"

[[contracts]]
fqn = "ownable_2step::Ownable2Step"

[[contracts]]
fqn = "cep18_token::Cep18"

[[contracts]]
fqn = "cep18::cep18_client_contract::Cep18ClientContract"
