[workspace]
members = [
    "odra",
    "odra-vm",
    "benchmark",
    "core",
    "examples",
    "examples/ourcoin",
    "modules",
    "odra-macros",
    "odra-casper/rpc-client",
    "odra-casper/livenet-env",
    "odra-casper/wasm-env",
    "odra-casper/test-vm",
    "odra-cli",
    "odra-schema",
    "odra-test",
    "odra-build",
    "odra-bdd",
]
exclude = [
    "odra-casper/proxy-caller",
    "templates/blank",
    "templates/full",
    "templates/workspace",
    "tests",
]
resolver = "2"

[workspace.package]
version = "2.3.1"
authors = [
    "Jakub Płaskonka <kuba@odra.dev>",
    "Krzysztof Pobiarżyn <krzysztof@odra.dev>",
    "Maciej Zieliński <maciej@odra.dev>",
]
license = "MIT"
homepage = "https://odra.dev/docs"
repository = "https://github.com/odradev/odra"

[workspace.dependencies]
odra-core = { path = "core", version = "2.3.1" }
odra-macros = { path = "odra-macros", version = "2.3.1" }
odra-casper-test-vm = { path = "odra-casper/test-vm", version = "2.3.1" }
odra-casper-rpc-client = { path = "odra-casper/rpc-client", version = "2.3.1" }
odra-vm = { path = "odra-vm", version = "2.3.1" }
odra-casper-wasm-env = { path = "odra-casper/wasm-env", version = "2.3.1" }
odra-schema = { path = "odra-schema", version = "2.3.1" }
casper-contract = { version = "5.1.0",  default-features = false }
casper-contract-schema = { version = "0.5.0" }
casper-types = "6.0.0"
casper-execution-engine = "8.1.0"
casper-engine-test-support = "8.1.0"
casper-storage = "2.0.0"
casper-event-standard = "0.7"
odra-casper-client = { version = "3.0.1", default-features = false }
blake2 = "0.10.6"
log = "0.4.20"
env_logger = "0.11.1"
serde = { version = "1.0.195", default-features = false }
serde_json = { version = "1.0.113", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
mockall = { version = "0.12.1" }
sha3 = { version = "0.10", default-features = false }
hex = "0.4"
tokio = "1.38"
base16 = { version = "0.2", default-features = false }
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
serde-json-wasm = { version = "1.0", default-features = false }
anyhow = { version = "1.0.86", default-features = false }
rand = { version = "0.9", default-features = false }
rand_chacha = { version = "0.9", default-features = false }
convert_case = "0.5.0"
lazy_static = "1.5.0"
cucumber = "0.21.1"
futures = "0.3.5"
derive_more = { version = "1.0.0", features = ["full"] }
project-root = "0.2.2"
backtrace = { version = "0.3" }

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
