[workspace]
members = [
    "odra",
    "odra-vm",
    "core",
    "odra-macros",
    "odra-casper/livenet-env",
    "odra-casper/casper-client",
    "odra-casper/wasm-env",
    "odra-casper/test-vm",
    "odra-test"]
exclude = [ "examples", "modules", "odra-casper/proxy-caller", "templates/blank", "templates/full", "templates/workspace"]
resolver = "2"

[workspace.package]
version = "0.8.0"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
homepage = "https://odra.dev/docs"
repository = "https://github.com/odradev/odra"

[workspace.dependencies]
casper-contract = { version = "3.0.0", default-features = false }
casper-types = { version = "3.0.0", default-features = false }
casper-execution-engine = "5.0.0"
casper-event-standard = "0.4.1"
blake2 = "0.10.6"
