[workspace]
members = [
    "core",
    "lang/codegen",
    "lang/ir",
    "lang/proc_macros",
    "mock_vm/backend",
    "mock_vm/types",
    "types",
    "utils",
    "odra-casper/backend",
    "odra-casper/codegen",
    "odra-casper/shared",
    "odra-casper/test_env",
    "odra-casper/types",
    "odra-casper/test_env/getter_proxy" 
]

exclude = [ "contract", "contract/builder", "examples", ]