[workspace]
members = [
    "core",
    "lang/generator",
    "lang/ir",
    "lang/proc_macros",
    "mock/vm",
    "mock/env",
    "mock/test_env",
    "modules",
    "test_env",
    "test_env/wrapper",
    "types",
]
