[workspace]
members = [
    "core",
    "lang/codegen",
    "lang/ir",
    "lang/proc_macros",
    "mock_vm",
    "types",
    "utils",
    "odra-casper/backend",
    "odra-casper/test_env",
    "odra-casper/shared",
]

exclude = [ "contract", "contract/builder" ]