[workspace]
members = [
    "core",
    "lang/codegen",
    "lang/ir",
    "lang/proc_macros",
    "mock_vm",
    "modules",
    "test_env",
    "test_env/wrapper",
    "types",
]

exclude = [
    "mycontract"
]
