[workspace]
members = [
    "core",
    "lang/codegen",
    "lang/ir",
    "lang/proc-macros",
    "mock-vm/backend",
    "mock-vm/types",
    "types",
    "utils",
    "odra-casper/backend",
    "odra-casper/codegen",
    "odra-casper/shared",
    "odra-casper/test-env",
    "odra-casper/types",
    "odra-casper/proxy-caller",
    "odra-casper/livenet"
]

exclude = [ "contract", "contract/builder", "examples", "modules" ]

[workspace.dependencies]
casper-contract = "3.0.0"
casper-types = "3.0.0"
casper-execution-engine = "5.0.0"
casper-event-standard = "0.4.0"