[workspace]
members = [
    "build",
    "core",
    "lang/codegen",
    "lang/ir",
    "lang/proc-macros",
    "mock-vm/backend",
    "mock-vm/types",
    "types",
    "utils",
    "odra-casper/backend",
    "odra-casper/codegen",
    "odra-casper/shared",
    "odra-casper/test-env",
    "odra-casper/types",
    "odra-casper/proxy-caller",
    "odra-casper/livenet"
]

exclude = [ "contract", "contract/builder", "examples", "modules" ]

[workspace.package]
version = "0.6.0"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
homepage = "https://odra.dev/docs"
repository = "https://github.com/odradev/odra"

[workspace.dependencies]
casper-contract = { version = "3.0.0", default-features = false }
casper-types = { version = "3.0.0", default-features = false }
casper-execution-engine = "5.0.0"
casper-event-standard = "0.4.0"