[workspace]
members = [
    "core",
    "lang/codegen",
    "lang/ir",
    "lang/proc_macros",
    "mock/vm",
    "mock/contract_env",
    "mock/test_env",
    "modules",
    "test_env",
    "test_env/wrapper",
    "types",
]

exclude = [
    "mycontract"
]
