[workspace]
exclude = [
  "odra-casper/proxy-caller",
  "templates/blank",
  "templates/full",
  "templates/workspace",
  "tests",
]
members = [
  "benchmark",
  "core",
  "examples",
  "examples/ourcoin",
  "modules",
  "odra",
  "odra-bdd",
  "odra-build",
  "odra-casper/livenet-env",
  "odra-casper/rpc-client",
  "odra-casper/test-vm",
  "odra-casper/wasm-env",
  "odra-cli",
  "odra-macros",
  "odra-schema",
  "odra-test",
  "odra-vm",
  "odra-wasm-client",
  "odra-wasm-client-builder",
]
resolver = "2"

[workspace.package]
authors = [
  "Jakub Płaskonka <kuba@odra.dev>",
  "Krzysztof Pobiarżyn <krzysztof@odra.dev>",
  "Maciej Zieliński <maciej@odra.dev>",
]
edition = "2021"
homepage = "https://odra.dev/docs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/odradev/odra"
version = "2.8.2"

[workspace.dependencies]
odra-casper-rpc-client = { path = "odra-casper/rpc-client", version = "2.8.2" }
odra-casper-test-vm = { path = "odra-casper/test-vm", version = "2.8.2" }
odra-casper-wasm-env = { path = "odra-casper/wasm-env", version = "2.8.2" }
odra-core = { path = "core", version = "2.8.2" }
odra-macros = { path = "odra-macros", version = "2.8.2" }
odra-schema = { path = "odra-schema", version = "2.8.2" }
odra-vm = { path = "odra-vm", version = "2.8.2" }
odra-wasm-client = { path = "odra-wasm-client", version = "2.8.2" }

casper-client = { version = "=5.0.0", default-features = false }
casper-contract = { version = "5.1", default-features = false }
casper-contract-schema = { version = "0.6.0" }
casper-engine-test-support = "8.1"
casper-event-standard = "0.7"
casper-execution-engine = "8.1"
casper-storage = "2.1"
casper-types = "6.1"

anyhow = { version = "1.0", default-features = false }
backtrace = { version = "0.3" }
base16 = { version = "0.2", default-features = false }
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
blake2 = "0.10"
bytes = "1.11"
chrono = { version = "0.4"}
clap = { version = "4.5"}
convert_case = "0.6"
cucumber = "0.21"
derive-try-from-ref = "0.1"
derive_more = { version = "2.1.0", features = ["full"] }
dotenv = "0.15"
futures = "0.3"
futures-util = "0.3"
gloo-utils = { version = "0.2"}
hex = "0.4"
itertools = "0.14"
js-sys = "0.3"
lazy_static = "1.5.0"
log = "0.4"
mockall = { version = "0.14" }
num-traits = { version = "0.2", default-features = false }
pretty_assertions = "1.4"
prettycli = "0.1"
proc-macro2 = "1.0"
project-root = "0.2"
quote = "1.0"
rand = { version = "0.9", default-features = false }
rand_chacha = { version = "0.9", default-features = false }
reqwest = { version = "0.12" }
rustyline = "14"
serde = { version = "1.0", default-features = false }
serde_derive = {  version = "1.0" }
serde-json-wasm = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false }
sha3 = { version = "0.10", default-features = false }
shlex = "1"
syn = "2.0"
syn_derive = "0.2"
thiserror = "1.0"
tokio = "1.48"
toml = "0.9"
wasm-bindgen = "=0.2.100"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3"}


[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
