flowchart TD
    prereqs[Install:\n Rust, WASM toolchain, wabt]

    prereqs --> 
        cargo_odra[cargo-odra:\n install, generate, build, test]
    
    cargo_odra -->
        flipper[Example:\n Flipper]

    base_types[Base types:\n Rust types, U256, U512, Address]

    base_types -->
        odra_type[OdraType] 

    module[Module:\n modularity, storage, entrypoints, env]

    module -->
        contract_env[Contract env]

    module -->
        host_env[Host env]

    host_env -->
        deployer[Deployer:\n deploy new contract]

    contract_env -->
        entrypoint[Entrypoint:\n mutability, name, args, ret]

    contract_env & odra_type -->
        storage[Storage:\n struct, fields]

    storage -->
        variable[Variable]

    storage -->
        sub_module[Submodule]

    storage -->
        mapping[Mapping]
