[package]
name = "odra-macros"
description = "Macros for Odra-based smart contracts."

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
convert_case = { workspace = true }
derive-try-from-ref = { workspace = true }
itertools = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["extra-traits", "full"] }
syn_derive = { workspace = true }

[dev-dependencies]
casper-types = { workspace = true }
pretty_assertions = "1.4.0"
prettyplease = "0.2.15"

[lib]
proc-macro = true

[lints.rust]
missing_docs = "warn"
