[package]
name = "odra-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odra = { path = "../core" }
odra-types = { path = "../types" }
casper-types = "3.0.0"