[package]
name = "odra-cosmos-types"
version = "0.2.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"

[dependencies]
odra-types = { path = "../../types" }
uint = "0.9.4"
hex = "0.4.3"
cosmwasm-std = "1.2.1"
serde_json = "1.0.91"
serde = { version = "1.0.152", features = ["derive"] }
