[package]
name = "odra-casper-test-env"
edition = "2021"
description = "Odra test environment for the Casper Blockchain."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
casper-execution-engine = { workspace = true }
casper-engine-test-support = { version = "7.0.1", features = ["test-support"] }
casper-types = { workspace = true }
odra-casper-shared = { path = "../shared", version = "0.6.1" }
odra-casper-types = { path = "../types", version = "0.6.1" }
odra-types = { path = "../../types", version = "0.6.1" }
odra-utils = { path = "../../utils", version = "0.6.1" }
colored = "=2.0.4"
