[package]
name = "odra-casper-test-env"
edition = "2021"
description = "Odra test environment for the Casper Blockchain."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
casper-engine-test-support = { version = "5.0.0", features = ["test-support"] }
casper-execution-engine = { workspace = true }
odra-casper-shared = { path = "../shared", version = "0.7.1" }
odra-types = { path = "../../types", version = "0.7.1" }
odra-utils = { path = "../../utils", version = "0.7.1" }
colored = "=2.0.4"