[package]
name = "odra-casper-test-env"
version = "0.3.1"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra"
description = "Odra test environment for the Casper Blockchain."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]

[dependencies]
casper-engine-test-support = { version = "4.0.0", features = ["test-support"] }
casper-execution-engine = { workspace = true }
casper-types = { workspace = true }
odra-casper-shared = { version = "0.3.1", path = "../shared" }
odra-casper-types = { version = "0.3.1", path = "../types" }
odra-types = { version = "0.3.1", path = "../../types" }
odra-utils = { version = "0.3.1", path = "../../utils" }
colored = "2.0.0"