[package]
name = "odra-vm-test-env"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odra-vm-machine = { path = "../machine" }
odra-core = { path = "../../odra-core" }
odra-types = { path = "../../types" }