[package]
description = "Wasm client"
name = "odra-wasm-client"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
odra-core = { workspace = true }

casper-client = { workspace = true }
casper-types = { workspace = true, features = ["datasize"] }

gloo-utils = { workspace = true, features = ["serde"] }
hex = { workspace = true }
js-sys = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["HtmlInputElement", "Response"] }

[lib]
crate-type = ["cdylib", "rlib"]
name = "odra_wasm_client"
path = "src/lib.rs"

[features]
cep18 = []
default = []
wcspr = []
