prepare:
    cargo install wasm-pack

build:
    wasm-pack build --target nodejs --release --out-dir pkg-nodejs .

build-web:
    wasm-pack build --target web --out-dir pkg-web .

run-web:
    cd examples/web && npm run start