[package]
name = "odra-proc-macros"
version = "0.1.0"
edition = "2018"

[dependencies]
proc-macro2 = "1.0.40"
quote = "1.0.19"
syn =  { version = "1.0.89", features = ["full", "extra-traits"] }
odra-ir = { path = "../ir" }
odra-codegen = { path = "../generator" }

[lib]
proc-macro = true
