[package]
name = "odra-casper-shared"
edition = "2021"
description = "Utilites uses by the Odra Casper-related crates."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
casper-event-standard = { workspace = true }
odra-casper-types = { path = "../types" }
odra-utils = { path = "../../utils" }
casper-contract = { version = "3.0.0", default-features = false, features = ["std", "test-support"] }
