[package]
name = "odra-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
odra-core = { path = "../core" }
anyhow = "1.0.75"
url = "2.4.1"
blake2 = { workspace = true }

[dev-dependencies]
odra-test = { path = "../odra-test" }