[package]
name = "flapper"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { path = "../../../odra/odra/odra", features = [], default-features = false }

[[bin]]
name = "build_contract"
path = "bin/build_contract.rs"
test = false

[[bin]]
name = "build_schema"
path = "bin/build_schema.rs"
test = false
