[package]
name = "odra-cli"
description = "Odra CLI - Command Line Interface for Odra smart contracts."
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true


[dependencies]
clap = { version = "4.5.21", features = ["derive", "cargo", "string"] }
prettycli = "0.1.1"
odra = { path = "../odra", version = "2.1.0", default-features = false }
odra-casper-livenet-env = { path = "../odra-casper/livenet-env", version = "2.1.0"}
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
serde_derive = { version = "1", features = ["default"] }
toml = "0.8.13"
project-root = { workspace = true }
pretty_assertions = "1.4.0"
anyhow = "1.0.86"
thiserror = "1.0.30"
hex = "0.4.3"
