[package]
name = "odra"
version = "0.2.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra"
description = "High-level smart contract framework for Rust."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm"]

[dependencies]
odra-utils = { version = "0.2.0", path = "../utils" }
odra-types = { version = "0.2.0", path = "../types" }
odra-proc-macros = { version = "0.2.0", path = "../lang/proc-macros" }
odra-mock-vm = { version = "0.2.0", path = "../mock-vm/backend", optional = true }
odra-casper-backend = { version = "0.2.0", path = "../odra-casper/backend", optional = true }
odra-casper-livenet = { version = "0.2.0", path = "../odra-casper/livenet", optional = true }
odra-casper-types = { version = "0.2.0", path = "../odra-casper/types", optional = true }
ref_thread_local = "0.1.1"
cfg-if = "1.0.0"
hex = "0.4.3"
num-traits = "0.2.14"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
odra-casper-test-env = { version = "0.2.0", path = "../odra-casper/test-env", optional = true }
odra-casper-codegen = { version = "0.2.0", path = "../odra-casper/codegen", optional = true }

[features]
default = [ "casper" ]
mock-vm = [ "odra-mock-vm" ]
casper = [ "odra-casper-backend", "odra-casper-test-env", "odra-casper-codegen", "odra-casper-types" ]
casper-livenet = [ "odra-casper-livenet", "odra-casper-types" ]
