[package]
name = "odra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odra-types = { path = "../types" }
odra-proc-macros = { path = "../lang/proc_macros" }
odra-mock-vm = { path = "../mock_vm", optional = true }
odra-test-env = { path = "../test_env",  default-features = false, optional = true  }
odra-test-env-wrapper = { path = "../test_env/wrapper", optional = true  }
ref_thread_local = "0.1.1"
cfg-if = "1.0.0"

[features]
default = [ "mock-vm" ]
mock-vm = [ "odra-mock-vm" ]
wasm = [ ]
wasm-test = [ "odra-test-env/wasm-test", "odra-test-env-wrapper" ]