[package]
name = "odra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odra-types = { git = "https://github.com/odradev/odra" }
odra-proc-macros = { git = "https://github.com/odradev/odra" }
odra-mock-env = { git = "https://github.com/odradev/odra", optional = true }
odra-mock-test-env = { git = "https://github.com/odradev/odra", optional = true }
odra-test-env = { git = "https://github.com/odradev/odra", optional = true  }
odra-test-env-wrapper = { git = "https://github.com/odradev/odra", optional = true  }
ref_thread_local = "0.1.1"
cfg-if = "1.0.0"

[features]
default = [ "mock-vm" ]
mock-vm = [ "odra-mock-env", "odra-mock-test-env", "odra-test-env/mock-vm" ]
wasm = [ ]
wasm-test = [ "odra-test-env/wasm-test", "odra-test-env-wrapper" ]