[package]
name = "odra"
edition = "2021"
description = "High-level smart contract framework for Rust."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm"]
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
odra-utils = { path = "../utils" }
odra-types = { path = "../types" }
odra-proc-macros = { path = "../lang/proc-macros" }
ref_thread_local = "0.1.1"
cfg-if = "1.0.0"
hex = "0.4.3"
num-traits = "0.2.14"
odra-mock-vm = { path = "../mock-vm/backend" }
odra-casper-backend = { path = "../odra-casper/backend" }
odra-casper-types = { path = "../odra-casper/types" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
odra-casper-test-env = { path = "../odra-casper/test-env" }
odra-casper-codegen = { path = "../odra-casper/codegen" }
odra-casper-livenet = { path = "../odra-casper/livenet" }

[build-dependencies]
odra-build = { path = "../build" }

#[features]
#default = [ "mock-vm" ]
#mock-vm = [ "odra-mock-vm" ]
#casper = [ "odra-casper-backend", "odra-casper-test-env", "odra-casper-codegen", "odra-casper-types" ]
#casper-livenet = [ "odra-casper-livenet", "odra-casper-types" ]
