[package]
name = "odra"
version = "0.1.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra"
description = "High-level smart contract framework for Rust."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm"]

[dependencies]
odra-utils = { version = "0.1.0", path = "../utils" }
odra-proc-macros = { version = "0.1.0", path = "../lang/proc_macros" }
odra-mock-vm = { version = "0.1.0", path = "../mock_vm/backend", optional = true }
odra-casper-backend = { version = "0.1.0", path = "../odra-casper/backend", optional = true }
ref_thread_local = "0.1.1"
cfg-if = "1.0.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
odra-casper-test-env = { version = "0.1.0", path = "../odra-casper/test_env", optional = true }

[features]
default = [ "mock-vm" ]
mock-vm = [ "odra-mock-vm" ]
casper = [ "odra-casper-backend", "odra-casper-test-env"]
