[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
#odra_dependency

[[bin]]
name = "build_contract"
path = "bin/build_contract.rs"
test = false

[[bin]]
name = "build_schema"
path = "bin/build_schema.rs"
test = false

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
