[package]
name = "odra-casper-backend"
edition = "2021"
description = "Odra backend bindings for the Casper Blockchain."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
odra-casper-shared = { path = "../shared", version = "0.6.1" }
odra-casper-types = { path = "../types", version = "0.6.1" }
odra-types = { path = "../../types", version = "0.6.1" }
casper-types = { workspace = true }
lazy_static = { version = "1.4.0", features = [ "spin_no_std" ] }
casper-event-standard = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
casper-contract = { workspace = true }
ink_allocator = { version = "4.2.1", default-features = false }
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
casper-contract = { workspace = true, default-features = false, features = ["test-support"] }