[package]
name = "odra-casper-backend"
edition = "2021"
description = "Odra backend bindings for the Casper Blockchain."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
odra-casper-shared = { path = "../shared" }
odra-casper-types = { path = "../types" }
odra-types = { path = "../../types" }
casper-contract = { version = "3.0.0", default-features = false, features = ["std", "test-support"] }
casper-types = { workspace = true }
syn = "1.0.96"
hex = "0.4.3"
lazy_static = "1.4.0"
casper-event-standard = { workspace = true }
sha256 = "1.1.4"
ed25519 = "1.2.0"