[package]
name = "odra-casper-backend"
version = "0.4.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra"
description = "Odra backend bindings for the Casper Blockchain."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]

[dependencies]
odra-casper-shared = { version = "0.4.0", path = "../shared" }
odra-casper-types = { version = "0.4.0", path = "../types" }
odra-types = { version = "0.4.0", path = "../../types" }
casper-contract = { version = "2.0.0", default-features = false, features = ["std", "test-support"] }
casper-types = { workspace = true }
syn = "1.0.96"
hex = "0.4.3"
lazy_static = "1.4.0"
casper-event-standard = { workspace = true }