[package]
name = "odra"
edition = "2021"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
odra-core = { workspace = true }
odra-macros = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
odra-casper-wasm-env = { path = "../odra-casper/wasm-env" }
