[package]
name = "odra-casper-getter-proxy"
version = "0.0.1"
edition = "2021"

[dependencies]
casper-contract = { version = "3.0.0" }
casper-types = "3.0.0"

[[bin]]
name = "getter_proxy"
path = "bin/getter_proxy.rs"
bench = false
doctest = false
test = false

[workspace]