[package]
name = "odra-casper-wasm-env"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", features = [ "spin_no_std" ] }
odra-core = { path = "../../core" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
casper-contract = { version = "3.0.0", default-features = false }
ink_allocator = { version = "4.2.1", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
casper-contract = { version = "3.0.0", default-features = false, features = ["test-support"] }