[package]
name = "odra-casper-test-env"
version = "0.1.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra-casper"
description = "Odra test environment for the Casper Blockchain."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]

[dependencies]
casper-engine-test-support = { version = "2.0.3", features = ["test-support"] }
casper-execution-engine = { version = "2.0.0" }
casper-types = "1.5.0"

odra-casper-shared = { version = "0.1.0", path = "../shared" }
# odra = { version = "0.1.0", default-features = false, features = [ "wasm-test" ] }
odra = { path = "../../odra/core", default-features = false, features = [ "wasm-test" ] }

[lib]
crate-type = ["cdylib"]
name = "odra_test_env"
