[package]
name = "odra-casper-proxy-caller"
description = "Proxy caller used by Odra Framework"

authors = [
  "Jakub Płaskonka <kuba@odra.dev>",
  "Krzysztof Pobiarżyn <krzysztof@odra.dev>",
  "Maciej Zieliński <maciej@odra.dev>",
]
edition = "2021"
homepage = "https://odra.dev/docs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/odradev/odra"
version = "2.9.1"

[dependencies]
odra-core = { path = "../../core" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
casper-contract = { version = "5.1", default-features = false }
ink_allocator = { version = "5.0.0", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
casper-contract = { version = "5.1", default-features = false, features = ["test-support"] }

[[bin]]
bench = false
doctest = false
name = "proxy_caller"
path = "bin/proxy_caller.rs"
test = false

[[bin]]
bench = false
doctest = false
name = "proxy_caller_with_return"
path = "bin/proxy_caller_with_return.rs"
test = false

[lints.rust]
missing_docs = "warn"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
