[package]
name = "odra-casper-proxy-caller"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
casper-contract = "3.0.0"
casper-types = { workspace = true }
odra-casper-shared = { path = "../shared" }

[[bin]]
name = "proxy_caller"
path = "bin/proxy_caller.rs"
bench = false
doctest = false
test = false

[[bin]]
name = "proxy_caller_with_return"
path = "bin/proxy_caller_with_return.rs"
bench = false
doctest = false
test = false