[package]
name = "odra-casper-proxy-caller"
edition = "2021"
version = "1.0.0"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
homepage = "https://odra.dev/docs"
repository = "https://github.com/odradev/odra"

[dependencies]
odra-core = { path = "../../core" }
odra-casper-wasm-env = { path = "../wasm-env" }

[[bin]]
name = "proxy_caller"
path = "bin/proxy_caller.rs"
bench = false
doctest = false
test = false

[[bin]]
name = "proxy_caller_with_return"
path = "bin/proxy_caller_with_return.rs"
bench = false
doctest = false
test = false

[lints.rust]
missing_docs = "warn"
