[package]
name = "odra-casper-proxy-caller"
edition = "2021"
version = "0.5.0"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
homepage = "https://odra.dev/docs"
repository = "https://github.com/odradev/odra"

[dependencies]
casper-contract = { version = "3.0.0", default-features = false }
casper-types = "3.0.0"
odra = { path = "../../odra" }
ink_allocator = { version = "4.2.1", default-features = false }

[[bin]]
name = "proxy_caller"
path = "bin/proxy_caller.rs"
bench = false
doctest = false
test = false

[[bin]]
name = "proxy_caller_with_return"
path = "bin/proxy_caller_with_return.rs"
bench = false
doctest = false
test = false