[package]
name = "odra-casper-proxy-caller"
description = "Proxy caller used by Odra Framework"

authors = [
  "Jakub Płaskonka <kuba@odra.dev>",
  "Krzysztof Pobiarżyn <krzysztof@odra.dev>",
  "Maciej Zieliński <maciej@odra.dev>",
]
edition = "2021"
homepage = "https://odra.dev/docs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/odradev/odra"
version = "2.7.2"

[dependencies]
odra-casper-wasm-env = { path = "../wasm-env" }
odra-core = { path = "../../core" }

[[bin]]
bench = false
doctest = false
name = "proxy_caller"
path = "bin/proxy_caller.rs"
test = false

[[bin]]
bench = false
doctest = false
name = "proxy_caller_with_return"
path = "bin/proxy_caller_with_return.rs"
test = false

[lints.rust]
missing_docs = "warn"
