[package]
name = "odra-examples"
version = "0.3.0"
edition = "2021"

[dependencies]
odra = { path = "../core", default-features = false }
odra-modules = { path = "../modules", default-features = false }

[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm", "odra-modules/mock-vm"]
casper = ["odra/casper", "odra-modules/mock-vm"]
casper-livenet = ["odra/casper-livenet", "odra-modules/casper-livenet"]

[[bin]]
name = "erc20-on-livenet"
path = "bin/erc20_on_livenet.rs"
required-features = ["casper-livenet"]
