[package]
name = "odra-examples"
version = "0.2.0"
edition = "2021"

[dependencies]
odra = { path = "../core", default-features = false }
odra-modules = { path = "../modules", default-features = false, optional = true }

[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm", "odra-modules/mock-vm"]
casper = ["odra/casper", "odra-modules/casper"]
cosmos = ["odra/cosmos", ]

[patch.crates-io]
casper-types = { git = "https://github.com/odradev/casper-node", branch = "feature/k256-update" }
