[package]
name = "odra-examples"
version = "0.5.0"
edition = "2021"

[dependencies]
odra = { path = "../core", default-features = false }
odra-modules = { path = "../modules", default-features = false }

[dev-dependencies]
sha256 = "1.1.4"
hex = "0.4.3"
casper-types = "3.0.0"

[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm", "odra-modules/mock-vm"]
casper = ["odra/casper", "odra-modules/casper"]
casper-livenet = ["odra/casper-livenet", "odra-modules/casper-livenet"]

[[bin]]
name = "erc20-on-livenet"
path = "bin/erc20_on_livenet.rs"
required-features = ["casper-livenet"]
