[package]
name = "odra-examples"
version = "0.8.0"
edition = "2021"

[dependencies]
odra = { path = "../odra", default-features = false }
casper-event-standard = "0.4.1"
odra-modules = { path = "../modules", default-features = false }
sha3 = { version = "0.10.6", default-features = false }

[dev-dependencies]
hex = "0.4.3"

[[bin]]
name = "build_contract"
path = "bin/build_contract.rs"

[[bin]]
name = "build_schema"
path = "bin/build_schema.rs"

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
#[[bin]]
#name = "erc20-on-livenet"
#path = "bin/erc20_on_livenet.rs"
#required-features = ["casper-livenet"]
