[package]
name = "odra-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odra = { path = "../core" }
borsh = "0.9.3"

[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm"]
