[package]
name = "odra-examples"
version = "0.5.0"
edition = "2021"

[dependencies]
odra = { path = "../core", default-features = false }
# odra-modules = { path = "../modules", default-features = false }
once_cell = "1.18.0"

[dev-dependencies]
hex = "0.4.3"

[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm"]
casper = ["odra/casper"]
casper-livenet = ["odra/casper-livenet"]

[[bin]]
name = "erc20-on-livenet"
path = "bin/erc20_on_livenet.rs"
required-features = ["casper-livenet"]
