[package]
name = "odra-examples"
version = "0.6.0"
edition = "2021"

[dependencies]
odra = { path = "../core" }
odra-modules = { path = "../modules"}

[dev-dependencies]
hex = "0.4.3"

[build-dependencies]
odra-build = { path = "../build" }

[[bin]]
name = "erc20-on-livenet"
path = "bin/erc20_on_livenet.rs"
