[[contracts]]
fqn = "contracts::owned_token::OwnedToken"

[[contracts]]
fqn = "contracts::balance_checker::BalanceChecker"

[[contracts]]
fqn = "contracts::token_manager::TokenManager"

[[contracts]]
fqn = "contracts::tlw::TimeLockWallet"

[[contracts]]
fqn = "features::reentrancy_guard::ReentrancyMock"

[[contracts]]
fqn = "features::signature_verifier::SignatureVerifier"

[[contracts]]
fqn = "features::module_nesting::NestedOdraTypesContract"

[[contracts]]
fqn = "features::storage::variable::DogContract"

[[contracts]]
fqn = "features::storage::mapping::DogContract2"

[[contracts]]
fqn = "features::storage::list::DogContract3"

[[contracts]]
fqn = "features::testing::TestingContract"

[[contracts]]
fqn = "features::host_functions::HostContract"

[[contracts]]
fqn = "features::handling_errors::OwnedContract"

[[contracts]]
fqn = "features::events::PartyContract"

[[contracts]]
fqn = "features::cross_calls::CrossContract"

[[contracts]]
fqn = "features::cross_calls::MathEngine"

[[contracts]]
fqn = "features::modules::ModulesContract"

[[contracts]]
fqn = "features::native_token::PublicWallet"

[[contracts]]
fqn = "features::access_control::MockModerated"

[[contracts]]
fqn = "features::pauseable::PauseableCounter"

[[contracts]]
fqn = "features::livenet::LivenetContract"
