[[contracts]]
name = "owned_token"
fqn = "odra_examples::owned_token::OwnedToken"

[[contracts]]
name = "balance_checker"
fqn = "odra_examples::balance_checker::BalanceChecker"

[[contracts]]
name = "ownable"
fqn = "odra_examples::ownable::Ownable"

[[contracts]]
name = "erc20"
fqn = "odra_examples::erc20::Erc20"

[[contracts]]
name = "wrapped_casper"
fqn = "odra_examples::wrapped_casper::WrappedCasper"
