[package]
name = "odra-casper-types"
version = "0.2.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra"
description = "Types used in the Casper enviorment."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]

[dependencies]
casper-types = { workspace = true }
odra-types = { version = "0.2.0", path = "../../types" }
casper-event-standard = "0.2.0"
num-traits = "0.2.14"
