[package]
name = "odra-casper-codegen"
edition = "2021"
description = "Odra codegen utility to generate Casper contracts."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
proc-macro2 = "1.0.39"
quote = "1.0.18"
syn = "1.0.96"
pretty_assertions = "1.2.1"
odra-casper-types = { path = "../types", version = "0.5.0" }
odra-casper-shared = { path = "../shared", version = "0.5.0" }
odra-types = { path = "../../types", version = "0.5.0" }
odra-utils = { path = "../../utils", version = "0.5.0" }
casper-types = { workspace = true }
casper-event-standard = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"