[package]
name = "odra-casper-codegen"
version = "0.4.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]
license = "MIT"
repository = "https://github.com/odradev/odra"
description = "Odra codegen utility to generate Casper contracts."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]

[dependencies]
proc-macro2 = "1.0.39"
quote = "1.0.18"
syn = "1.0.96"
pretty_assertions = "1.2.1"
odra-casper-types = { version = "0.4.0", path = "../types" }
odra-types = { version = "0.4.0", path = "../../types" }
odra-utils = { version = "0.4.0", path = "../../utils" }
casper-types = { workspace = true }
casper-event-standard = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"