[package]
name = "examples2"
version = "0.1.0"
edition = "2021"

[dependencies]
odra2 = { path = "../odra2" }

[[bin]]
name = "counter"
path = "src/lib.rs"

[[bin]]
name = "counter_pack"
path = "src/lib.rs"

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
