[package]
name = "odra-casper-test-vm"
edition = "2021"
description = "Odra test environment for the Casper Blockchain."
keywords = ["wasm", "webassembly", "blockchain"]
categories = ["wasm", "smart contracts"]
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
casper-engine-test-support = { version = "5.0.0", features = ["test-support"] }
casper-execution-engine = { workspace = true }
odra-core = { path = "../../core" }
odra-types = { path = "../../types" }
odra-casper-shared = { path = "../shared" }
casper-event-standard = "0.4.0"
odra-utils = { path = "../../utils" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
casper-contract = { workspace = true }
ink_allocator = { version = "4.2.1", default-features = false }
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
casper-contract = { version = "3.0.0", default-features = false, features = ["test-support"] }
