[workspace]
members = [
    "flipper",
    "flapper",
    ]
resolver = "2"

[workspace.dependencies]
#odra_dependency

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
