use odra::{casper_types::{bytesrepr::Bytes, U256}, prelude::*};
use odra_modules::cep95::{CEP95Interface, Cep95};

/// A module definition. Each module struct consists Vars and Mappings
/// or/and another modules.
#[odra::module]
pub struct MyToken {
    /// A sub-module that implements the CEP-95 token standard.
    token: SubModule<Cep95>,
}

/// Module implementation.
///
/// To generate entrypoints,
/// an implementation block must be marked as #[odra::module].
#[odra::module]
impl MyToken {

    /// Initializes the contract with the given parameters.
    pub fn init(&mut self, name: String, symbol: String) {
        self.token.name.set(name);
        self.token.symbol.set(symbol);
    }

    delegate! {
        to self.token {
            fn name(&self) -> String;
            fn symbol(&self) -> String;
            fn balance_of(&self, owner: Address) -> U256;
            fn owner_of(&self, token_id: U256) -> Option<Address>;
            fn safe_transfer_from(&mut self, from: Address, to: Address, token_id: U256, data: Option<Bytes>);
            fn transfer_from(&mut self, from: Address, to: Address, token_id: U256);
            fn approve(&mut self, spender: Address, token_id: U256);
            fn revoke_approval(&mut self, token_id: U256);
            fn approved_for(&self, token_id: U256) -> Option<Address>;
            fn approve_for_all(&mut self, operator: Address);
            fn revoke_approval_for_all(&mut self, operator: Address);
            fn is_approved_for_all(&self, owner: Address, operator: Address) -> bool;
            fn token_metadata(&self, token_id: U256) -> Vec<(String, String)>;
        }
    }

    /// Mints a new token with the given ID and metadata to the specified address.
    /// Only the contract owner can call this function.
    pub fn mint(&mut self, to: Address, token_id: U256, metadata: Vec<(String, String)>) {
        self.token.mint(to, token_id, metadata);
    }

    /// Burns the token with the given ID.
    /// Only the token owner can call this function.
    /// This function will remove the token from the owner's balance and delete its metadata.
    pub fn burn(&mut self, token_id: U256) {
        self.token.burn(token_id);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use odra::host::Deployer;

    #[test]
    fn it_works() {
        let env = odra_test::env();
        // To test a module we need to deploy it. Autogenerated `MyTokenInitArgs`
        // implements `InitArgs` trait and `MyToken` implements `Deployer` trait,
        // so we can use it to deploy the module.
        let init_args = MyTokenInitArgs {
            name: "MyToken".to_string(),
            symbol: "MT".to_string(),
        };
        assert!(MyToken::try_deploy(&env, init_args).is_ok());
    }
}
