[package]
name = "odra-casper-rpc-client"
description = "RPC Client for the Casper Node."
edition = "2021"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
odra-core = { workspace = true }
casper-types = { workspace = true, features = ["std-fs-io"] }
casper-client = { workspace = true }

serde_json = { version = "1.0", features = ["raw_value"] }
itertools = "0.10.5"
dotenv = "0.15.0"
prettycli = "0.1.1"
thiserror = "1.0.40"
base16 = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
toml = "0.8.20"
rand = "0.8.5"
