[package]
name = "odra-casper-rpc-client"
description = "RPC Client for the Casper Node."
edition = "2021"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
odra-core = { workspace = true }
odra-schema = { workspace = true }
casper-execution-engine = { workspace = true }
casper-hashing = "3.0.0"
jsonrpc-lite = "0.6.0"
serde_json = { version = "1.0", features = ["raw_value"] }
serde = "1.0"
log = "0.4.20"
hex = "0.4.3"
reqwest = { version = "0.11.16", features = ["blocking", "json"] }
datasize = "0.2.14"
schemars = "0.8.5"
itertools = "0.10.5"
blake2 = { version = "0.9.1", default-features = false }
dotenv = "0.15.0"
prettycli = "0.1.1"
thiserror = "1.0.40"
bytes = "1.5.0"
anyhow = "1.0.86"
humantime = "2.1.0"