[package]
name = "odra-macros"
version = "0.1.0"
edition = "2018"

[dependencies]
proc-macro2 = "1.0.40"
quote = "1.0.19"
convert_case = "0.5.0"
syn =  { version = "1.0.89", features = ["full", "extra-traits"] }

[lib]
proc-macro = true
