[package]
name = "odra-cosmos-test-env"
version = "0.2.0"
edition = "2021"
authors = ["Jakub Płaskonka <kuba@odra.dev>", "Krzysztof Pobiarżyn <krzysztof@odra.dev>", "Maciej Zieliński <maciej@odra.dev>"]

[dependencies]
odra-cosmos-shared = { version = "0.2.0", path = "../shared" }
odra-cosmos-types = { version = "0.2.0", path = "../types" }
odra-types = { version = "0.2.0", path = "../../types" }
odra-utils = { version = "0.2.0", path = "../../utils" }
cosmwasm-std = "1.2.1"
cosmwasm-vm = "1.2.1"
serde = { version = "1.0.152", features = [ "derive" ]  }
schemars = "0.8.3"
schemars_derive = "0.8.3"
serde_json = "1.0.91"
convert_case = "0.5.0"
