[package]
name = "odra-casper-livenet-env"
version = "0.1.0"
edition = "2021"

[dependencies]
odra-core = { path = "../../core", default-features = false }
odra-casper-client = { path = "../casper-client" }
blake2 = { workspace = true }
log = "0.4.20"