[package]
name = "odra-casper-livenet-env"
description = "Odra's backend for interacting with the Casper Node."
edition = "2021"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
odra-core = { workspace = true }
odra-casper-rpc-client = { workspace = true }
casper-types = { workspace = true, default-features = false }
blake2 = { workspace = true }
log = { workspace = true }
dotenv = "0.15.0"
tokio = { version = "1.0", features = ["rt"] }

[dev-dependencies]
curve25519-parser = "0.3.0"

[lints.rust]
missing_docs = "warn"

[features]
default = ["odra-casper-rpc-client/livenet", "casper-types/std"]
no_std = ["odra-casper-rpc-client/no-std"]