[package]
description = "Odra's backend for interacting with the Casper Node."
name = "odra-casper-livenet-env"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
odra-casper-rpc-client = { workspace = true }
odra-core = { workspace = true }
odra-schema = { workspace = true }

anyhow = { workspace = true }
blake2 = { workspace = true }
log = { workspace = true }
project-root = { workspace = true }
serde_json = { workspace = true }

[lints.rust]
missing_docs = "warn"
