[package]
name = "odra-vm-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
odra-vm-machine = { path = "../machine" }
odra-core = { path = "../../odra-core" }
odra-types = { path = "../../types" }