[package]
name = "odra-ir"
version = "0.1.0"
edition = "2018"

[dependencies]
proc-macro2 = "1.0.40"
proc-macro-error = "1.0.4"
quote = "1.0.19"
syn = { version = "1.0.89", features = [ "parsing", "full", "visit", "extra-traits", "derive" ] }
itertools = "0.10.3"