name: Benchmark

on:
  push:
    branches:
      - 'release/**'
      - 'feature/**'
    paths-ignore:
      - '**.md'

run-name: Benchmarking gas costs for ${{ github.head_ref }}

jobs:
  benchmark:
    name: Benchmark
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - uses: extractions/setup-just@v1
        name: Setup just
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions-rs/toolchain@v1
        name: Setup toolchain
        with:
          target: wasm32-unknown-unknown
      - name: Cache target
        uses: actions/cache@v2
        with:
          path: target
          key: odra-target-folder
      - run: just prepare-test-env
        name: Prepare test environment
      - run: just benchmark
        name: Run benchmark
      - run: echo "BENCHMARK_FILENAME=${GITHUB_REF_NAME}" | sed 's:/:-:g' | sed 's:\.:-:g' >> $GITHUB_ENV
        name: Set benchmark filename
      - uses: actions/upload-artifact@v4
        name: Upload benchmark results
        with:
          name: ${{ env.BENCHMARK_FILENAME }}
          path: benchmark/gas_report.json
      - uses: actions/upload-artifact@v4
        name: Upload benchmark results
        with:
          name: release
          path: benchmark/gas_report.json
