name: Coverage

on:
  pull_request:
    branches-ignore:
      - 'hotfix/**'
    paths-ignore:
      - '**.md'

run-name: Calculating coverage for ${{ github.head_ref }}

jobs:
  coverage:
    name: Calculate test coverage
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Setup just
        uses: extractions/setup-just@v1
      - name: Cache target
        uses: actions/cache@v2
        with:
          path: target
          key: odra-target-folder
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          components: rustfmt, clippy, llvm-tools-preview
      - name: Prepare test environment
        run: just prepare-test-env
      - name: Run coverage tests
        run: just coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: target/coverage/*.lcov
