name: odra-ci

on:
  push:
    branches:
      - '[0-9].[0-9]+.[0-9]+'
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - '[0-9].[0-9]+.[0-9]+'
      - feature/**
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Run cargo clippy checks
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
