name: odra-ci

on:
  push:
    branches:
      - 'release/**'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - 'release/**'
      - 'feature/**'
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
      - run: git config --global user.email "you@example.com" && git config --global user.name "Your Name" # remove when it is fixed 
      - run: just fix-casper-node # remove when it is fixed
      - run: just check-lint
      - run: just prepare-test-env
      - run: just test
