name: odra-ci

on:
  push:
    branches:
      - 'release/**'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - 'release/**'
      - 'feature/**'
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: buildjet-8vcpu-ubuntu-2204
    services:
      casper-nctl:
        image: makesoftware/casper-nctl:latest
        options: --name mynctl
        env:
          PREDEFINED_ACCOUNTS: 'true'
          MINIMUM_ROUND_EXPONENT: '12'
          MAXIMUM_ROUND_EXPONENT: '14'
          DEPLOY_DELAY: '12sec'
        ports:
          - 11101:11101
    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          components: rustfmt, clippy, llvm-tools-preview
      - run: just check-lint
      - run: just prepare-test-env
      - run: just test
      - run: just test-livenet
      - run: just coverage
      - uses: codecov/codecov-action@v3
        with:
          files: target/coverage/*.lcov