name: odra-ci

on:
  push:
    branches:
      - 'release/**'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - 'release/**'
      - 'feature/**'
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          components: rustfmt, clippy, llvm-tools-preview
      - run: just check-lint
      - run: just prepare-test-env
      - run: just coverage
      - run: just test
      - uses: codecov/codecov-action@v3
        with:
          files: target/coverage/*.lcov