name: odra-ci

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - master
      - develop
      - feature/*
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt -- --check
      - name: Run cargo clippy checks
        uses: actions-rs/cargo@v1
        with:
          command: clippy --all-targets -- -D warnings
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          