name: Tests

on:
  pull_request:
    branches:
      - 'release/**'
      - 'feature/**'
    paths-ignore:
      - '**.md'

run-name: Running lints and tests for ${{ github.head_ref }}

jobs:
  test:
    name: Test
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - uses: extractions/setup-just@v1
        name: Setup just
#      - uses: actions/checkout@v2
#        name: Checkout code
#      - name: Cache target
#        uses: actions/cache@v2
#        with:
#          path: target
#          key: odra-target-folder
#      - uses: actions-rs/toolchain@v1
#        name: Setup toolchain
#        with:
#          target: wasm32-unknown-unknown
#          components: rustfmt, clippy, llvm-tools-preview
#      - run: just check-lint
#        name: Run lints
#      - run: just prepare-test-env
#        name: Prepare test environment
#      - run: just test
#        name: Run tests