name: Tests

on:
  pull_request:
    branches-ignore:
      - 'hotfix/**'
    paths-ignore:
      - '**.md'
  push:
    branches:
      - 'release/**'
    paths-ignore:
      - '**.md'

run-name: Running lints and tests for ${{ github.head_ref }}

jobs:
  test:
    name: Test
    runs-on: buildjet-8vcpu-ubuntu-2204
    services:
      casper-nctl:
        image: makesoftware/casper-nctl:v203
        options: --name mynctl
        env:
          PREDEFINED_ACCOUNTS: 'true'
          MINIMUM_ROUND_EXPONENT: '12'
          MAXIMUM_ROUND_EXPONENT: '14'
          DEPLOY_DELAY: '30sec'
        ports:
          - 11101:11101
    steps:
      - name: Setup just
        uses: extractions/setup-just@v1
      - name: Set key for speculative execution
        run: echo "WASM_CLIENT_SK=${{ secrets.CLIENT_SK }}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/debug/.fingerprint
            target/debug/build
          key: odra-cache
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-01-01
          target: wasm32-unknown-unknown
          components: rustfmt, clippy, llvm-tools-preview
      - name: Run lints
        run: just check-lint
      - name: Prepare test environment
        run: just prepare-test-env
      - name: Run tests
        run: just test
      - name: Run livenet tests
        run: just test-livenet